name: flutter_template
description: "A new Flutter project template."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.2
  flutter: ^3.27.4

dependencies:
  animations: ^2.0.11
  another_flushbar: ^1.12.30
  email_validator: ^3.0.0
  flag: ^7.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.3.0
  http_parser: ^4.1.2
  intl: any
  json_annotation: ^4.9.0
  phone_form_field: ^10.0.4
  pinput: ^5.0.1
  shared_preferences: ^2.5.1

dependency_overrides:
  source_gen: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.14
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  import_sorter: ^4.6.0
  json_serializable: ^6.9.3

import_sorter:
  emojis: false
  comments: false
  # ignored_files: # Optional, defaults to []
  #   - \/lib\/*

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/svgs/
    - assets/fonts/

  fonts:
    # - family: CustomIcons
    #   fonts:
    #     - asset: assets/fonts/CustomIcons.ttf
    # Font used for page headlines.
    - family: Jua
      fonts:
        - asset: assets/fonts/Jua-Regular.ttf
          weight: 400

    # Font used for English glyphs.
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900

    # Font used for Georgian glyphs.
    - family: NotoSansGeorgian
      fonts:
        - asset: assets/fonts/NotoSansGeorgian-Thin.ttf
          weight: 100
        - asset: assets/fonts/NotoSansGeorgian-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NotoSansGeorgian-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSansGeorgian-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansGeorgian-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansGeorgian-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSansGeorgian-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansGeorgian-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NotoSansGeorgian-Black.ttf
          weight: 900
